from tensorflow import keras

BATCH_SIZE=1
CONV_BASE_SIZE = 16
#CONV_ACTIVATION ='relu'
CONV_ACTIVATION = keras.layers.LeakyReLU(0.1)
GRID_SIZE=(2,2)
GRID_CELL_BOXES=1
INPUT_SIZE=(448,448)
LSTM_SIZE = 16*CONV_BASE_SIZE
SEQUENCE_LENGTH = 5
VALIDATION_SPLIT=0.1

YOLO_LAYERS_COUNTS = [1,2,2,1] #[2,8,8,4]
